### ISSUE TITLE
Convolving arbitrary full-polarization complex-valued beams

### ISSUE THREAD

**Issue by kmbasad** [cosmo-ethz/hide#3]
I read in your paper that arbitrary beams (e.g. fits files) can be used. Is there a straightforward way to do this? Or should I try to write a function following (e.g.) the function you use to load gsm fits files? I can try to to do this, but just wondering if you already have the functionality to load arbitrary beam fits files.

And does your code perform convolution for all Stokes parameters? So e.g. if I give a full polarization beam, shall I see the effects of polarization leakage?

**Comment by jakeret** [comment]
HIDE doesn't provide a loading mechanism for beams. However, writing a new implementation is relatively easy. Have a look at one of the current implementations: https://github.com/cosmo-ethz/hide/blob/master/hide/beam/airy_disk.py
